### ISSUE TITLE
Daemonize does not appear to function as intended

### ISSUE THREAD

**Issue by GWustenstein** [uhppoted/uhppoted-tunnel#1]
Hi There-  
When I invoke the following per the readme, 
sudo /home/pi/uhppoted/uhppoted-tunnel daemonize max-retries -1 --max-retry-delay 5m --out udp/broadcast:255.255.255.255:60000 --in tls/client:[redacted] --ca-cert /home/pi/uhppoted/actrl-ca-crt.pem --cert /home/pi/uhppoted/actrl-ctrl-crt.pem --key /home/pi/uhppoted/actrl-ctrl-key.pem
it throws "flag provided but not defined: -daemonize" followed with the usage list.  If I run ./uhppoted-tunnel help, the synopsis shows the daemonize command at the end of the argument list, which if I do it simply runs the command on the session, no installing the service.

In my setup, I have a remote VPS set up as a tls server in/out, and running everything on the command line works as intended and runs great, but it all goes to hell when log out of one of the endpoints (including leaving the pid file around as a nice annoyance), so getting to run as a service as intended for both the pivot node and the remote endpoint would be really nice.

Also, I figured out the hard way one could not specify the ethernet port for the out udp/broadcast interface, with that, the pi could hop it on a wifi, and securely TLS it out to where it needs to go, no cables needed.  Instead, the pi sees eth0 up and it jacks the router up to the point wifi won't work (yes, it's Bullseye...)
Thanks,
-GW

**Comment by uhppoted** [comment]
Well, that's embarrassing .. there was a typo in the service name.

I've pushed a set of fixes to the `main` branch so you'll need to pull that and rebuild it - the `build-all` target in the Makefile will build a binary for the RaspberryPi if you're not building on the Pi itself.

I don't have a free Raspberry Pi at the moment but have tested _daemonize_/_undaemonize_ on Debian 11/Bullseye and  they do seem to be working now. 

BTW, `daemonize` only supports the _--in_, _--out_ and _--label_ options - it doesn't currently support the `--max-retries`,  `--max-retry-delay`, `--ca-cert`, `---cert` or `--key`  options which may be why you are getting "_flag provided but not defined_" error. The service uses the defaults, which are:

- `--max-retries`: 32
- `--max-retry-delay`: 5m
- `--udp-timeout`: 5s
- `--ca-cert`: ca.cert
- `--cert`: client.cert
- `--key`: client.key or server.key 
- `--client-auth`: false

The certificate and key files are expected to be in the runtime directory i.e. the directory from which the service was installed (or set in the service file).

re. ethernet port. The `udp/broadcast` interface is the pipe to the actual controller so it will use the wired LAN for the _out_ port. The _in_ port should be able to connect via wifi though?

**Comment by GWustenstein** [comment]
Okay, great!
Now, I can think of the following issues:  The defaults work well for the endpoints, but the 'pivot' node (the VPS running as a TLS server) ideally should not be an 'open relay' and should run as a service in client-auth mode.  Further to that, reuse of client keys should be discouraged, especially given the fact that these are remote and if physically accessed, it would not be difficult to yoink the keys AND the server address off the SD card.  Taken to it's logical conclusion, single shared key at one compromised location used across a VPS hub would provide physical access to every location, so I'd rather wait before going through the effort of doing a build for three platforms, eh?

**Comment by uhppoted** [comment]
Not entirely sure I follow your threat model - can you explain how a physically compromised endpoint would provide access to the rest of the system?

BTW:
- the client keys need only be signed by the root CA i.e. they don't need to be shared (think you have it like that already?)
- the _daemonize_ command doesn't take all the parameters but if you edit the service file you can add them to the `ExecStart` line e.g. 
```
...
[Service]
Type=simple
ExecStart=/opt/uhppoted/bin/uhppoted-tunnel --lockfile /var/uhppoted/tunnel/uhppoted-tunnel-qwerty.pid --in  tls/server:0.0.0.0:12345 --out tls/server:0.0.0.0:54321 --client-auth
...
```

**Comment by GWustenstein** [comment]
Oh, cool, that should be documented!
What I meant to say, without --client-auth at the relay node, anyone with access to one endpoint can essentially take control of the endpoints, but now I see you can set that manually so while not straight-forward it is usable.  Thank you very much!

**Comment by uhppoted** [comment]
Great - glad that works for you!

re. documented. Editing the service file is a workaround and not ideal - I think the better long term option is going to be a something like a configuration file but it needs some thinking about.

(tracking issue is [here](https://github.com/uhppoted/uhppoted-tunnel/issues/2)

**Comment by GWustenstein** [comment]
A config file is totally the way to go.  

Woke up this morning thinking that long and verbose init or command lines are hard to read and debug.  They're also potential security issues as you potentially leak config details through common tools like ps (I know, security through obscurity yada yada but let's not leave the door wide open...)

Again, thanks for the help, and finding a work-around so quickly.  It's up and running, and I've been watching events trickle in from a remote door controller across town.  Even tried to attack both the endpoint and the VPS a few different and hideous ways and it seems pretty solid.  Next step is to build (or wait for the next stable rel) and daemonize this mess...  I guess I should leave this open for now until release?

**Comment by uhppoted** [comment]
re. events. Very cool! Thanks for letting me know! 

The next release is a good couple of weeks away (there are a bunch of small fixes and some documentation spread across all the repositories that need to happen first) so if you want to put it to bed you may have to build it yourself.

And, yup, happy to leave this open until it's released.

**Comment by uhppoted** [comment]
Closing - fix released in [v0.8.2](https://github.com/uhppoted/uhppoted-tunnel/releases/tag/v0.8.2).

Feel free to reopen if necessary.

**Comment by GWustenstein** [comment]
After a week's run on the command line with no errors at all, decided to give daemonize a go...
Whelp, for some reason it can't find the default ssl files:

Oct 24 12:13:54 [...] systemd[1]: Started UHPPOTE UTO311-L0x access card controllers UDP tunnel service/daemon.
Oct 24 12:13:54 [...] uhppoted-tunnel[167174]: 2022/10/24 12:13:54 uhppoted-tunnel service v0.8.2 - Linux (PID 167174)
Oct 24 12:13:54 [...] uhppoted-tunnel[167174]: ERROR: open ca.cert: no such file or directory
Oct 24 12:13:54 [...] systemd[1]: uhppoted-tunnel-pivot_server.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 12:13:54 [...] systemd[1]: uhppoted-tunnel-pivot_server.service: Failed with result 'exit-code'.

I stuck them in /etc/uhppoted, /etc/uhppoted, /etc/uhppoted/tunnel, still can't find them, where is it looking?

When I edit the unit file as you described previously with explicit file references, the service appears to start just fine

**Comment by uhppoted** [comment]
It defaults to the current working directory:
```
./bin/uhppoted-tunnel help

  Usage: uhppoted-tunnel [options] <command> [parameters]

  Commands:
    daemonize     Daemonizes uhppoted-tunnel as a service/daemon
    undaemonize   Deregisters uhppoted-tunnel as a service/daemon
    version       Displays the current version
    help          Displays this message. For help on a specific command use 'uhppoted-tunnel help <command>'

  Defaults to 'run'.

   'run' options:
    --ca-cert      File path for CA certificate PEM file (defaults to ca.cert)
    --cert         File path for client/server TLS certificate PEM file (defaults to client.cert or server.cert)
 ```
 
The reason being that you can have multiple tunnels running on a machine (and hence multiple tunnel daemons) and they probably each need a separate set of certificates and keys - so by default they look in their 'own' directory. And you can choose to override the defaults either by specifying the location with either a command line argument or by setting the working directory in the service file.
